name: Testes Regressivos

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
  schedule:
    - cron: "18,22,24,26 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Install Google Chrome
      run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome*.deb

    - uses: nanasess/setup-chromedriver@v1
    - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
    
    - name: Build with Maven
      run: mvn test -Dtest**/*RunCucumberTest cluecumber-report:reporting

    - name: Test Reporter
      uses: dorny/test-reporter@v1.4.3
      with:
        name: runTest
        path: "**/surefire-reports/TEST-*.xml"
        reporter: java-junit